# Generated by Django 4.2.3 on 2023-12-27 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("Standard", "Estándar"),
                            ("Premium", "Premium"),
                            ("VIP", "VIP"),
                        ],
                        max_length=20,
                    ),
                ),
                ("available_rooms", models.PositiveIntegerField(default=0)),
                ("max_capacity", models.PositiveIntegerField(default=4)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reservas_hotel.hotel",
                    ),
                ),
            ],
        ),
    ]
