# Generated by Django 4.2.3 on 2023-12-27 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("reservas_hotel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Habitacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("Standard", "Estándar"),
                            ("Premium", "Premium"),
                            ("VIP", "VIP"),
                        ],
                        max_length=10,
                    ),
                ),
                ("disponible", models.BooleanField(default=True)),
                ("capacidad_maxima", models.PositiveIntegerField(default=4)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reservas_hotel.hotel",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Room",
        ),
    ]
