# Generated by Django 4.2.3 on 2023-12-27 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("reservas_hotel", "0002_habitacion_delete_room"),
    ]

    operations = [
        migrations.CreateModel(
            name="AsignacionHabitacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField(default=1)),
                (
                    "habitacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reservas_hotel.habitacion",
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reservas_hotel.hotel",
                    ),
                ),
            ],
        ),
    ]
